### ISSUE TITLE
Take screenshot in selectable resolution

### ISSUE THREAD

**Issue by klausdorer** [Gama11/RoboViz#56] opened 2015-06-04 07:12 UTC
It would be great to have the possibility to choose a resolution in which a "screen shot" is done. Not sure if this is easily possible. For press purposes or other publishing things it is hard to get a screen with high enough resolution for high quality screen shots. (enhancement)

**Comment by Gama11** [comment] 2015-06-04 07:14
Duplicate of #6. ;)

**Closed by Gama11** 2015-06-04 07:14 UTC
